changelog:
  exclude:
    labels:
      - omit-release-notes
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: New Features
      labels:
        - enhancement
    - title: Bug Fixes
      labels:
        - bug-fix
    - title: Other Changes
      labels:
        - "*"
